// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

/**
 * <pre>
 * rpc clientConnect -------------------------------------------------------------------------------
 * </pre>
 *
 * Protobuf type {@code kibbutz.ClientInfo}
 */
public  final class ClientInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kibbutz.ClientInfo)
    ClientInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientInfo.newBuilder() to construct.
  private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientInfo() {
    clientUsername_ = "";
    clientPubKey_ = com.google.protobuf.ByteString.EMPTY;
    routerUsername_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientUsername_ = s;
            break;
          }
          case 18: {

            clientPubKey_ = input.readBytes();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            routerUsername_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            research.bwsharingapp.proto.kb.ClientInfo.class, research.bwsharingapp.proto.kb.ClientInfo.Builder.class);
  }

  public static final int CLIENTUSERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientUsername_;
  /**
   * <code>string clientUsername = 1;</code>
   */
  public java.lang.String getClientUsername() {
    java.lang.Object ref = clientUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientUsername_ = s;
      return s;
    }
  }
  /**
   * <code>string clientUsername = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientUsernameBytes() {
    java.lang.Object ref = clientUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTPUBKEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString clientPubKey_;
  /**
   * <code>bytes clientPubKey = 2;</code>
   */
  public com.google.protobuf.ByteString getClientPubKey() {
    return clientPubKey_;
  }

  public static final int ROUTERUSERNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object routerUsername_;
  /**
   * <code>string routerUsername = 3;</code>
   */
  public java.lang.String getRouterUsername() {
    java.lang.Object ref = routerUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      routerUsername_ = s;
      return s;
    }
  }
  /**
   * <code>string routerUsername = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRouterUsernameBytes() {
    java.lang.Object ref = routerUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      routerUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientUsername_);
    }
    if (!clientPubKey_.isEmpty()) {
      output.writeBytes(2, clientPubKey_);
    }
    if (!getRouterUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, routerUsername_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientUsername_);
    }
    if (!clientPubKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, clientPubKey_);
    }
    if (!getRouterUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, routerUsername_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof research.bwsharingapp.proto.kb.ClientInfo)) {
      return super.equals(obj);
    }
    research.bwsharingapp.proto.kb.ClientInfo other = (research.bwsharingapp.proto.kb.ClientInfo) obj;

    boolean result = true;
    result = result && getClientUsername()
        .equals(other.getClientUsername());
    result = result && getClientPubKey()
        .equals(other.getClientPubKey());
    result = result && getRouterUsername()
        .equals(other.getRouterUsername());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientUsername().hashCode();
    hash = (37 * hash) + CLIENTPUBKEY_FIELD_NUMBER;
    hash = (53 * hash) + getClientPubKey().hashCode();
    hash = (37 * hash) + ROUTERUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRouterUsername().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(research.bwsharingapp.proto.kb.ClientInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * rpc clientConnect -------------------------------------------------------------------------------
   * </pre>
   *
   * Protobuf type {@code kibbutz.ClientInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kibbutz.ClientInfo)
      research.bwsharingapp.proto.kb.ClientInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              research.bwsharingapp.proto.kb.ClientInfo.class, research.bwsharingapp.proto.kb.ClientInfo.Builder.class);
    }

    // Construct using research.bwsharingapp.proto.kb.ClientInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      clientUsername_ = "";

      clientPubKey_ = com.google.protobuf.ByteString.EMPTY;

      routerUsername_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientInfo_descriptor;
    }

    public research.bwsharingapp.proto.kb.ClientInfo getDefaultInstanceForType() {
      return research.bwsharingapp.proto.kb.ClientInfo.getDefaultInstance();
    }

    public research.bwsharingapp.proto.kb.ClientInfo build() {
      research.bwsharingapp.proto.kb.ClientInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public research.bwsharingapp.proto.kb.ClientInfo buildPartial() {
      research.bwsharingapp.proto.kb.ClientInfo result = new research.bwsharingapp.proto.kb.ClientInfo(this);
      result.clientUsername_ = clientUsername_;
      result.clientPubKey_ = clientPubKey_;
      result.routerUsername_ = routerUsername_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof research.bwsharingapp.proto.kb.ClientInfo) {
        return mergeFrom((research.bwsharingapp.proto.kb.ClientInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(research.bwsharingapp.proto.kb.ClientInfo other) {
      if (other == research.bwsharingapp.proto.kb.ClientInfo.getDefaultInstance()) return this;
      if (!other.getClientUsername().isEmpty()) {
        clientUsername_ = other.clientUsername_;
        onChanged();
      }
      if (other.getClientPubKey() != com.google.protobuf.ByteString.EMPTY) {
        setClientPubKey(other.getClientPubKey());
      }
      if (!other.getRouterUsername().isEmpty()) {
        routerUsername_ = other.routerUsername_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      research.bwsharingapp.proto.kb.ClientInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (research.bwsharingapp.proto.kb.ClientInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object clientUsername_ = "";
    /**
     * <code>string clientUsername = 1;</code>
     */
    public java.lang.String getClientUsername() {
      java.lang.Object ref = clientUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientUsername = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientUsernameBytes() {
      java.lang.Object ref = clientUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientUsername = 1;</code>
     */
    public Builder setClientUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientUsername_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientUsername = 1;</code>
     */
    public Builder clearClientUsername() {
      
      clientUsername_ = getDefaultInstance().getClientUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string clientUsername = 1;</code>
     */
    public Builder setClientUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientUsername_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString clientPubKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes clientPubKey = 2;</code>
     */
    public com.google.protobuf.ByteString getClientPubKey() {
      return clientPubKey_;
    }
    /**
     * <code>bytes clientPubKey = 2;</code>
     */
    public Builder setClientPubKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientPubKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes clientPubKey = 2;</code>
     */
    public Builder clearClientPubKey() {
      
      clientPubKey_ = getDefaultInstance().getClientPubKey();
      onChanged();
      return this;
    }

    private java.lang.Object routerUsername_ = "";
    /**
     * <code>string routerUsername = 3;</code>
     */
    public java.lang.String getRouterUsername() {
      java.lang.Object ref = routerUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routerUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string routerUsername = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRouterUsernameBytes() {
      java.lang.Object ref = routerUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routerUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string routerUsername = 3;</code>
     */
    public Builder setRouterUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      routerUsername_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string routerUsername = 3;</code>
     */
    public Builder clearRouterUsername() {
      
      routerUsername_ = getDefaultInstance().getRouterUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string routerUsername = 3;</code>
     */
    public Builder setRouterUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      routerUsername_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kibbutz.ClientInfo)
  }

  // @@protoc_insertion_point(class_scope:kibbutz.ClientInfo)
  private static final research.bwsharingapp.proto.kb.ClientInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new research.bwsharingapp.proto.kb.ClientInfo();
  }

  public static research.bwsharingapp.proto.kb.ClientInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientInfo>
      PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
    public ClientInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientInfo> getParserForType() {
    return PARSER;
  }

  public research.bwsharingapp.proto.kb.ClientInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

