// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientUsername = 1;</code>
   */
  java.lang.String getClientUsername();
  /**
   * <code>string clientUsername = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientUsernameBytes();

  /**
   * <code>bytes clientPubKey = 2;</code>
   */
  com.google.protobuf.ByteString getClientPubKey();

  /**
   * <code>string routerUsername = 3;</code>
   */
  java.lang.String getRouterUsername();
  /**
   * <code>string routerUsername = 3;</code>
   */
  com.google.protobuf.ByteString
      getRouterUsernameBytes();
}
