// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface ClientIOUReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.ClientIOUReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 statusCode = 1;</code>
   */
  int getStatusCode();
}
