// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface ClientIOUSignedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.ClientIOUSigned)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
   */
  boolean hasClientIOU();
  /**
   * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
   */
  research.bwsharingapp.proto.kb.ClientIOU getClientIOU();
  /**
   * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
   */
  research.bwsharingapp.proto.kb.ClientIOUOrBuilder getClientIOUOrBuilder();

  /**
   * <code>bytes sign = 2;</code>
   */
  com.google.protobuf.ByteString getSign();
}
