// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

/**
 * Protobuf type {@code kibbutz.ClientIOUSigned}
 */
public  final class ClientIOUSigned extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kibbutz.ClientIOUSigned)
    ClientIOUSignedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientIOUSigned.newBuilder() to construct.
  private ClientIOUSigned(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientIOUSigned() {
    sign_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientIOUSigned(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            research.bwsharingapp.proto.kb.ClientIOU.Builder subBuilder = null;
            if (clientIOU_ != null) {
              subBuilder = clientIOU_.toBuilder();
            }
            clientIOU_ = input.readMessage(research.bwsharingapp.proto.kb.ClientIOU.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clientIOU_);
              clientIOU_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {

            sign_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOUSigned_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOUSigned_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            research.bwsharingapp.proto.kb.ClientIOUSigned.class, research.bwsharingapp.proto.kb.ClientIOUSigned.Builder.class);
  }

  public static final int CLIENTIOU_FIELD_NUMBER = 1;
  private research.bwsharingapp.proto.kb.ClientIOU clientIOU_;
  /**
   * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
   */
  public boolean hasClientIOU() {
    return clientIOU_ != null;
  }
  /**
   * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
   */
  public research.bwsharingapp.proto.kb.ClientIOU getClientIOU() {
    return clientIOU_ == null ? research.bwsharingapp.proto.kb.ClientIOU.getDefaultInstance() : clientIOU_;
  }
  /**
   * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
   */
  public research.bwsharingapp.proto.kb.ClientIOUOrBuilder getClientIOUOrBuilder() {
    return getClientIOU();
  }

  public static final int SIGN_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString sign_;
  /**
   * <code>bytes sign = 2;</code>
   */
  public com.google.protobuf.ByteString getSign() {
    return sign_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clientIOU_ != null) {
      output.writeMessage(1, getClientIOU());
    }
    if (!sign_.isEmpty()) {
      output.writeBytes(2, sign_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clientIOU_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClientIOU());
    }
    if (!sign_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, sign_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof research.bwsharingapp.proto.kb.ClientIOUSigned)) {
      return super.equals(obj);
    }
    research.bwsharingapp.proto.kb.ClientIOUSigned other = (research.bwsharingapp.proto.kb.ClientIOUSigned) obj;

    boolean result = true;
    result = result && (hasClientIOU() == other.hasClientIOU());
    if (hasClientIOU()) {
      result = result && getClientIOU()
          .equals(other.getClientIOU());
    }
    result = result && getSign()
        .equals(other.getSign());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClientIOU()) {
      hash = (37 * hash) + CLIENTIOU_FIELD_NUMBER;
      hash = (53 * hash) + getClientIOU().hashCode();
    }
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientIOUSigned parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(research.bwsharingapp.proto.kb.ClientIOUSigned prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kibbutz.ClientIOUSigned}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kibbutz.ClientIOUSigned)
      research.bwsharingapp.proto.kb.ClientIOUSignedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOUSigned_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOUSigned_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              research.bwsharingapp.proto.kb.ClientIOUSigned.class, research.bwsharingapp.proto.kb.ClientIOUSigned.Builder.class);
    }

    // Construct using research.bwsharingapp.proto.kb.ClientIOUSigned.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (clientIOUBuilder_ == null) {
        clientIOU_ = null;
      } else {
        clientIOU_ = null;
        clientIOUBuilder_ = null;
      }
      sign_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOUSigned_descriptor;
    }

    public research.bwsharingapp.proto.kb.ClientIOUSigned getDefaultInstanceForType() {
      return research.bwsharingapp.proto.kb.ClientIOUSigned.getDefaultInstance();
    }

    public research.bwsharingapp.proto.kb.ClientIOUSigned build() {
      research.bwsharingapp.proto.kb.ClientIOUSigned result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public research.bwsharingapp.proto.kb.ClientIOUSigned buildPartial() {
      research.bwsharingapp.proto.kb.ClientIOUSigned result = new research.bwsharingapp.proto.kb.ClientIOUSigned(this);
      if (clientIOUBuilder_ == null) {
        result.clientIOU_ = clientIOU_;
      } else {
        result.clientIOU_ = clientIOUBuilder_.build();
      }
      result.sign_ = sign_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof research.bwsharingapp.proto.kb.ClientIOUSigned) {
        return mergeFrom((research.bwsharingapp.proto.kb.ClientIOUSigned)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(research.bwsharingapp.proto.kb.ClientIOUSigned other) {
      if (other == research.bwsharingapp.proto.kb.ClientIOUSigned.getDefaultInstance()) return this;
      if (other.hasClientIOU()) {
        mergeClientIOU(other.getClientIOU());
      }
      if (other.getSign() != com.google.protobuf.ByteString.EMPTY) {
        setSign(other.getSign());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      research.bwsharingapp.proto.kb.ClientIOUSigned parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (research.bwsharingapp.proto.kb.ClientIOUSigned) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private research.bwsharingapp.proto.kb.ClientIOU clientIOU_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.ClientIOU, research.bwsharingapp.proto.kb.ClientIOU.Builder, research.bwsharingapp.proto.kb.ClientIOUOrBuilder> clientIOUBuilder_;
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public boolean hasClientIOU() {
      return clientIOUBuilder_ != null || clientIOU_ != null;
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public research.bwsharingapp.proto.kb.ClientIOU getClientIOU() {
      if (clientIOUBuilder_ == null) {
        return clientIOU_ == null ? research.bwsharingapp.proto.kb.ClientIOU.getDefaultInstance() : clientIOU_;
      } else {
        return clientIOUBuilder_.getMessage();
      }
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public Builder setClientIOU(research.bwsharingapp.proto.kb.ClientIOU value) {
      if (clientIOUBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientIOU_ = value;
        onChanged();
      } else {
        clientIOUBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public Builder setClientIOU(
        research.bwsharingapp.proto.kb.ClientIOU.Builder builderForValue) {
      if (clientIOUBuilder_ == null) {
        clientIOU_ = builderForValue.build();
        onChanged();
      } else {
        clientIOUBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public Builder mergeClientIOU(research.bwsharingapp.proto.kb.ClientIOU value) {
      if (clientIOUBuilder_ == null) {
        if (clientIOU_ != null) {
          clientIOU_ =
            research.bwsharingapp.proto.kb.ClientIOU.newBuilder(clientIOU_).mergeFrom(value).buildPartial();
        } else {
          clientIOU_ = value;
        }
        onChanged();
      } else {
        clientIOUBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public Builder clearClientIOU() {
      if (clientIOUBuilder_ == null) {
        clientIOU_ = null;
        onChanged();
      } else {
        clientIOU_ = null;
        clientIOUBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public research.bwsharingapp.proto.kb.ClientIOU.Builder getClientIOUBuilder() {
      
      onChanged();
      return getClientIOUFieldBuilder().getBuilder();
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    public research.bwsharingapp.proto.kb.ClientIOUOrBuilder getClientIOUOrBuilder() {
      if (clientIOUBuilder_ != null) {
        return clientIOUBuilder_.getMessageOrBuilder();
      } else {
        return clientIOU_ == null ?
            research.bwsharingapp.proto.kb.ClientIOU.getDefaultInstance() : clientIOU_;
      }
    }
    /**
     * <code>.kibbutz.ClientIOU clientIOU = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.ClientIOU, research.bwsharingapp.proto.kb.ClientIOU.Builder, research.bwsharingapp.proto.kb.ClientIOUOrBuilder> 
        getClientIOUFieldBuilder() {
      if (clientIOUBuilder_ == null) {
        clientIOUBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            research.bwsharingapp.proto.kb.ClientIOU, research.bwsharingapp.proto.kb.ClientIOU.Builder, research.bwsharingapp.proto.kb.ClientIOUOrBuilder>(
                getClientIOU(),
                getParentForChildren(),
                isClean());
        clientIOU_ = null;
      }
      return clientIOUBuilder_;
    }

    private com.google.protobuf.ByteString sign_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes sign = 2;</code>
     */
    public com.google.protobuf.ByteString getSign() {
      return sign_;
    }
    /**
     * <code>bytes sign = 2;</code>
     */
    public Builder setSign(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes sign = 2;</code>
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kibbutz.ClientIOUSigned)
  }

  // @@protoc_insertion_point(class_scope:kibbutz.ClientIOUSigned)
  private static final research.bwsharingapp.proto.kb.ClientIOUSigned DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new research.bwsharingapp.proto.kb.ClientIOUSigned();
  }

  public static research.bwsharingapp.proto.kb.ClientIOUSigned getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientIOUSigned>
      PARSER = new com.google.protobuf.AbstractParser<ClientIOUSigned>() {
    public ClientIOUSigned parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientIOUSigned(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientIOUSigned> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientIOUSigned> getParserForType() {
    return PARSER;
  }

  public research.bwsharingapp.proto.kb.ClientIOUSigned getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

