// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

/**
 * Protobuf type {@code kibbutz.ClientIOU}
 */
public  final class ClientIOU extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kibbutz.ClientIOU)
    ClientIOUOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientIOU.newBuilder() to construct.
  private ClientIOU(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientIOU() {
    clientUsername_ = "";
    server_ = "";
    nonce_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientIOU(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            research.bwsharingapp.proto.kb.TrafficInfo.Builder subBuilder = null;
            if (in_ != null) {
              subBuilder = in_.toBuilder();
            }
            in_ = input.readMessage(research.bwsharingapp.proto.kb.TrafficInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(in_);
              in_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            research.bwsharingapp.proto.kb.TrafficInfo.Builder subBuilder = null;
            if (out_ != null) {
              subBuilder = out_.toBuilder();
            }
            out_ = input.readMessage(research.bwsharingapp.proto.kb.TrafficInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(out_);
              out_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            clientUsername_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            server_ = s;
            break;
          }
          case 42: {

            nonce_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOU_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOU_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            research.bwsharingapp.proto.kb.ClientIOU.class, research.bwsharingapp.proto.kb.ClientIOU.Builder.class);
  }

  public static final int IN_FIELD_NUMBER = 1;
  private research.bwsharingapp.proto.kb.TrafficInfo in_;
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  public boolean hasIn() {
    return in_ != null;
  }
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfo getIn() {
    return in_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : in_;
  }
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getInOrBuilder() {
    return getIn();
  }

  public static final int OUT_FIELD_NUMBER = 2;
  private research.bwsharingapp.proto.kb.TrafficInfo out_;
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  public boolean hasOut() {
    return out_ != null;
  }
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfo getOut() {
    return out_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : out_;
  }
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getOutOrBuilder() {
    return getOut();
  }

  public static final int CLIENTUSERNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object clientUsername_;
  /**
   * <code>string clientUsername = 3;</code>
   */
  public java.lang.String getClientUsername() {
    java.lang.Object ref = clientUsername_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientUsername_ = s;
      return s;
    }
  }
  /**
   * <code>string clientUsername = 3;</code>
   */
  public com.google.protobuf.ByteString
      getClientUsernameBytes() {
    java.lang.Object ref = clientUsername_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientUsername_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVER_FIELD_NUMBER = 4;
  private volatile java.lang.Object server_;
  /**
   * <code>string server = 4;</code>
   */
  public java.lang.String getServer() {
    java.lang.Object ref = server_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      server_ = s;
      return s;
    }
  }
  /**
   * <code>string server = 4;</code>
   */
  public com.google.protobuf.ByteString
      getServerBytes() {
    java.lang.Object ref = server_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      server_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NONCE_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString nonce_;
  /**
   * <code>bytes nonce = 5;</code>
   */
  public com.google.protobuf.ByteString getNonce() {
    return nonce_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (in_ != null) {
      output.writeMessage(1, getIn());
    }
    if (out_ != null) {
      output.writeMessage(2, getOut());
    }
    if (!getClientUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientUsername_);
    }
    if (!getServerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, server_);
    }
    if (!nonce_.isEmpty()) {
      output.writeBytes(5, nonce_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (in_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIn());
    }
    if (out_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOut());
    }
    if (!getClientUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientUsername_);
    }
    if (!getServerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, server_);
    }
    if (!nonce_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, nonce_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof research.bwsharingapp.proto.kb.ClientIOU)) {
      return super.equals(obj);
    }
    research.bwsharingapp.proto.kb.ClientIOU other = (research.bwsharingapp.proto.kb.ClientIOU) obj;

    boolean result = true;
    result = result && (hasIn() == other.hasIn());
    if (hasIn()) {
      result = result && getIn()
          .equals(other.getIn());
    }
    result = result && (hasOut() == other.hasOut());
    if (hasOut()) {
      result = result && getOut()
          .equals(other.getOut());
    }
    result = result && getClientUsername()
        .equals(other.getClientUsername());
    result = result && getServer()
        .equals(other.getServer());
    result = result && getNonce()
        .equals(other.getNonce());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIn()) {
      hash = (37 * hash) + IN_FIELD_NUMBER;
      hash = (53 * hash) + getIn().hashCode();
    }
    if (hasOut()) {
      hash = (37 * hash) + OUT_FIELD_NUMBER;
      hash = (53 * hash) + getOut().hashCode();
    }
    hash = (37 * hash) + CLIENTUSERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientUsername().hashCode();
    hash = (37 * hash) + SERVER_FIELD_NUMBER;
    hash = (53 * hash) + getServer().hashCode();
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getNonce().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.ClientIOU parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(research.bwsharingapp.proto.kb.ClientIOU prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kibbutz.ClientIOU}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kibbutz.ClientIOU)
      research.bwsharingapp.proto.kb.ClientIOUOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOU_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              research.bwsharingapp.proto.kb.ClientIOU.class, research.bwsharingapp.proto.kb.ClientIOU.Builder.class);
    }

    // Construct using research.bwsharingapp.proto.kb.ClientIOU.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (inBuilder_ == null) {
        in_ = null;
      } else {
        in_ = null;
        inBuilder_ = null;
      }
      if (outBuilder_ == null) {
        out_ = null;
      } else {
        out_ = null;
        outBuilder_ = null;
      }
      clientUsername_ = "";

      server_ = "";

      nonce_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_ClientIOU_descriptor;
    }

    public research.bwsharingapp.proto.kb.ClientIOU getDefaultInstanceForType() {
      return research.bwsharingapp.proto.kb.ClientIOU.getDefaultInstance();
    }

    public research.bwsharingapp.proto.kb.ClientIOU build() {
      research.bwsharingapp.proto.kb.ClientIOU result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public research.bwsharingapp.proto.kb.ClientIOU buildPartial() {
      research.bwsharingapp.proto.kb.ClientIOU result = new research.bwsharingapp.proto.kb.ClientIOU(this);
      if (inBuilder_ == null) {
        result.in_ = in_;
      } else {
        result.in_ = inBuilder_.build();
      }
      if (outBuilder_ == null) {
        result.out_ = out_;
      } else {
        result.out_ = outBuilder_.build();
      }
      result.clientUsername_ = clientUsername_;
      result.server_ = server_;
      result.nonce_ = nonce_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof research.bwsharingapp.proto.kb.ClientIOU) {
        return mergeFrom((research.bwsharingapp.proto.kb.ClientIOU)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(research.bwsharingapp.proto.kb.ClientIOU other) {
      if (other == research.bwsharingapp.proto.kb.ClientIOU.getDefaultInstance()) return this;
      if (other.hasIn()) {
        mergeIn(other.getIn());
      }
      if (other.hasOut()) {
        mergeOut(other.getOut());
      }
      if (!other.getClientUsername().isEmpty()) {
        clientUsername_ = other.clientUsername_;
        onChanged();
      }
      if (!other.getServer().isEmpty()) {
        server_ = other.server_;
        onChanged();
      }
      if (other.getNonce() != com.google.protobuf.ByteString.EMPTY) {
        setNonce(other.getNonce());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      research.bwsharingapp.proto.kb.ClientIOU parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (research.bwsharingapp.proto.kb.ClientIOU) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private research.bwsharingapp.proto.kb.TrafficInfo in_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> inBuilder_;
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public boolean hasIn() {
      return inBuilder_ != null || in_ != null;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo getIn() {
      if (inBuilder_ == null) {
        return in_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : in_;
      } else {
        return inBuilder_.getMessage();
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder setIn(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (inBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        in_ = value;
        onChanged();
      } else {
        inBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder setIn(
        research.bwsharingapp.proto.kb.TrafficInfo.Builder builderForValue) {
      if (inBuilder_ == null) {
        in_ = builderForValue.build();
        onChanged();
      } else {
        inBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder mergeIn(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (inBuilder_ == null) {
        if (in_ != null) {
          in_ =
            research.bwsharingapp.proto.kb.TrafficInfo.newBuilder(in_).mergeFrom(value).buildPartial();
        } else {
          in_ = value;
        }
        onChanged();
      } else {
        inBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder clearIn() {
      if (inBuilder_ == null) {
        in_ = null;
        onChanged();
      } else {
        in_ = null;
        inBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo.Builder getInBuilder() {
      
      onChanged();
      return getInFieldBuilder().getBuilder();
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getInOrBuilder() {
      if (inBuilder_ != null) {
        return inBuilder_.getMessageOrBuilder();
      } else {
        return in_ == null ?
            research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : in_;
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> 
        getInFieldBuilder() {
      if (inBuilder_ == null) {
        inBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder>(
                getIn(),
                getParentForChildren(),
                isClean());
        in_ = null;
      }
      return inBuilder_;
    }

    private research.bwsharingapp.proto.kb.TrafficInfo out_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> outBuilder_;
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public boolean hasOut() {
      return outBuilder_ != null || out_ != null;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo getOut() {
      if (outBuilder_ == null) {
        return out_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : out_;
      } else {
        return outBuilder_.getMessage();
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder setOut(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (outBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        out_ = value;
        onChanged();
      } else {
        outBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder setOut(
        research.bwsharingapp.proto.kb.TrafficInfo.Builder builderForValue) {
      if (outBuilder_ == null) {
        out_ = builderForValue.build();
        onChanged();
      } else {
        outBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder mergeOut(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (outBuilder_ == null) {
        if (out_ != null) {
          out_ =
            research.bwsharingapp.proto.kb.TrafficInfo.newBuilder(out_).mergeFrom(value).buildPartial();
        } else {
          out_ = value;
        }
        onChanged();
      } else {
        outBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder clearOut() {
      if (outBuilder_ == null) {
        out_ = null;
        onChanged();
      } else {
        out_ = null;
        outBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo.Builder getOutBuilder() {
      
      onChanged();
      return getOutFieldBuilder().getBuilder();
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getOutOrBuilder() {
      if (outBuilder_ != null) {
        return outBuilder_.getMessageOrBuilder();
      } else {
        return out_ == null ?
            research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : out_;
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> 
        getOutFieldBuilder() {
      if (outBuilder_ == null) {
        outBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder>(
                getOut(),
                getParentForChildren(),
                isClean());
        out_ = null;
      }
      return outBuilder_;
    }

    private java.lang.Object clientUsername_ = "";
    /**
     * <code>string clientUsername = 3;</code>
     */
    public java.lang.String getClientUsername() {
      java.lang.Object ref = clientUsername_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientUsername_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientUsername = 3;</code>
     */
    public com.google.protobuf.ByteString
        getClientUsernameBytes() {
      java.lang.Object ref = clientUsername_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientUsername_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientUsername = 3;</code>
     */
    public Builder setClientUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientUsername_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientUsername = 3;</code>
     */
    public Builder clearClientUsername() {
      
      clientUsername_ = getDefaultInstance().getClientUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string clientUsername = 3;</code>
     */
    public Builder setClientUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientUsername_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object server_ = "";
    /**
     * <code>string server = 4;</code>
     */
    public java.lang.String getServer() {
      java.lang.Object ref = server_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        server_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string server = 4;</code>
     */
    public com.google.protobuf.ByteString
        getServerBytes() {
      java.lang.Object ref = server_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string server = 4;</code>
     */
    public Builder setServer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      server_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string server = 4;</code>
     */
    public Builder clearServer() {
      
      server_ = getDefaultInstance().getServer();
      onChanged();
      return this;
    }
    /**
     * <code>string server = 4;</code>
     */
    public Builder setServerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      server_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes nonce = 5;</code>
     */
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }
    /**
     * <code>bytes nonce = 5;</code>
     */
    public Builder setNonce(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes nonce = 5;</code>
     */
    public Builder clearNonce() {
      
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kibbutz.ClientIOU)
  }

  // @@protoc_insertion_point(class_scope:kibbutz.ClientIOU)
  private static final research.bwsharingapp.proto.kb.ClientIOU DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new research.bwsharingapp.proto.kb.ClientIOU();
  }

  public static research.bwsharingapp.proto.kb.ClientIOU getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientIOU>
      PARSER = new com.google.protobuf.AbstractParser<ClientIOU>() {
    public ClientIOU parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientIOU(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientIOU> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientIOU> getParserForType() {
    return PARSER;
  }

  public research.bwsharingapp.proto.kb.ClientIOU getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

