// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface ClientConnectReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.ClientConnectReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool clientExists = 1;</code>
   */
  boolean getClientExists();

  /**
   * <code>int32 statusCode = 2;</code>
   */
  int getStatusCode();

  /**
   * <code>string statusMsg = 3;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();

  /**
   * <code>bytes nonce = 4;</code>
   */
  com.google.protobuf.ByteString getNonce();
}
