// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public final class KibbutzProto {
  private KibbutzProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kibbutz_TrafficInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kibbutz_TrafficInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kibbutz_ClientIOU_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kibbutz_ClientIOU_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kibbutz_RouterIOU_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kibbutz_RouterIOU_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kibbutz_RouterIOUReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kibbutz_RouterIOUReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rkibbutz.proto\022\007kibbutz\"D\n\013TrafficInfo\022" +
      "\014\n\004pkts\030\001 \001(\003\022\r\n\005bytes\030\002 \001(\003\022\013\n\003src\030\003 \001(" +
      "\t\022\013\n\003dst\030\004 \001(\t\"~\n\tClientIOU\022 \n\002in\030\001 \001(\0132" +
      "\024.kibbutz.TrafficInfo\022!\n\003out\030\002 \001(\0132\024.kib" +
      "butz.TrafficInfo\022\016\n\006client\030\003 \001(\t\022\016\n\006serv" +
      "er\030\004 \001(\t\022\014\n\004sign\030\005 \001(\t\"\205\001\n\tRouterIOU\022 \n\002" +
      "in\030\001 \001(\0132\024.kibbutz.TrafficInfo\022!\n\003out\030\002 " +
      "\001(\0132\024.kibbutz.TrafficInfo\022\014\n\004sign\030\003 \001(\t\022" +
      "%\n\tclientIou\030\004 \001(\0132\022.kibbutz.ClientIOU\"5" +
      "\n\016RouterIOUReply\022\017\n\007isValid\030\001 \001(\010\022\022\n\nsta",
      "tusCode\030\002 \001(\0052I\n\007Kibbutz\022>\n\rsendRouterIO" +
      "U\022\022.kibbutz.RouterIOU\032\027.kibbutz.RouterIO" +
      "UReply\"\000B6\n\036research.bwsharingapp.proto." +
      "kbB\014KibbutzProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kibbutz_TrafficInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kibbutz_TrafficInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kibbutz_TrafficInfo_descriptor,
        new java.lang.String[] { "Pkts", "Bytes", "Src", "Dst", });
    internal_static_kibbutz_ClientIOU_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kibbutz_ClientIOU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kibbutz_ClientIOU_descriptor,
        new java.lang.String[] { "In", "Out", "Client", "Server", "Sign", });
    internal_static_kibbutz_RouterIOU_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kibbutz_RouterIOU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kibbutz_RouterIOU_descriptor,
        new java.lang.String[] { "In", "Out", "Sign", "ClientIou", });
    internal_static_kibbutz_RouterIOUReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kibbutz_RouterIOUReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kibbutz_RouterIOUReply_descriptor,
        new java.lang.String[] { "IsValid", "StatusCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
