// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface RegisterUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.RegisterUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>int32 statusCode = 2;</code>
   */
  int getStatusCode();
}
