// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

/**
 * Protobuf type {@code kibbutz.RouterIOUSigned}
 */
public  final class RouterIOUSigned extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kibbutz.RouterIOUSigned)
    RouterIOUSignedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouterIOUSigned.newBuilder() to construct.
  private RouterIOUSigned(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouterIOUSigned() {
    sign_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouterIOUSigned(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            research.bwsharingapp.proto.kb.RouterIOU.Builder subBuilder = null;
            if (routerIou_ != null) {
              subBuilder = routerIou_.toBuilder();
            }
            routerIou_ = input.readMessage(research.bwsharingapp.proto.kb.RouterIOU.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(routerIou_);
              routerIou_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {

            sign_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOUSigned_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOUSigned_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            research.bwsharingapp.proto.kb.RouterIOUSigned.class, research.bwsharingapp.proto.kb.RouterIOUSigned.Builder.class);
  }

  public static final int ROUTERIOU_FIELD_NUMBER = 1;
  private research.bwsharingapp.proto.kb.RouterIOU routerIou_;
  /**
   * <code>.kibbutz.RouterIOU routerIou = 1;</code>
   */
  public boolean hasRouterIou() {
    return routerIou_ != null;
  }
  /**
   * <code>.kibbutz.RouterIOU routerIou = 1;</code>
   */
  public research.bwsharingapp.proto.kb.RouterIOU getRouterIou() {
    return routerIou_ == null ? research.bwsharingapp.proto.kb.RouterIOU.getDefaultInstance() : routerIou_;
  }
  /**
   * <code>.kibbutz.RouterIOU routerIou = 1;</code>
   */
  public research.bwsharingapp.proto.kb.RouterIOUOrBuilder getRouterIouOrBuilder() {
    return getRouterIou();
  }

  public static final int SIGN_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString sign_;
  /**
   * <code>bytes sign = 2;</code>
   */
  public com.google.protobuf.ByteString getSign() {
    return sign_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (routerIou_ != null) {
      output.writeMessage(1, getRouterIou());
    }
    if (!sign_.isEmpty()) {
      output.writeBytes(2, sign_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (routerIou_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRouterIou());
    }
    if (!sign_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, sign_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof research.bwsharingapp.proto.kb.RouterIOUSigned)) {
      return super.equals(obj);
    }
    research.bwsharingapp.proto.kb.RouterIOUSigned other = (research.bwsharingapp.proto.kb.RouterIOUSigned) obj;

    boolean result = true;
    result = result && (hasRouterIou() == other.hasRouterIou());
    if (hasRouterIou()) {
      result = result && getRouterIou()
          .equals(other.getRouterIou());
    }
    result = result && getSign()
        .equals(other.getSign());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRouterIou()) {
      hash = (37 * hash) + ROUTERIOU_FIELD_NUMBER;
      hash = (53 * hash) + getRouterIou().hashCode();
    }
    hash = (37 * hash) + SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getSign().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.RouterIOUSigned parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(research.bwsharingapp.proto.kb.RouterIOUSigned prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kibbutz.RouterIOUSigned}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kibbutz.RouterIOUSigned)
      research.bwsharingapp.proto.kb.RouterIOUSignedOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOUSigned_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOUSigned_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              research.bwsharingapp.proto.kb.RouterIOUSigned.class, research.bwsharingapp.proto.kb.RouterIOUSigned.Builder.class);
    }

    // Construct using research.bwsharingapp.proto.kb.RouterIOUSigned.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (routerIouBuilder_ == null) {
        routerIou_ = null;
      } else {
        routerIou_ = null;
        routerIouBuilder_ = null;
      }
      sign_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOUSigned_descriptor;
    }

    public research.bwsharingapp.proto.kb.RouterIOUSigned getDefaultInstanceForType() {
      return research.bwsharingapp.proto.kb.RouterIOUSigned.getDefaultInstance();
    }

    public research.bwsharingapp.proto.kb.RouterIOUSigned build() {
      research.bwsharingapp.proto.kb.RouterIOUSigned result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public research.bwsharingapp.proto.kb.RouterIOUSigned buildPartial() {
      research.bwsharingapp.proto.kb.RouterIOUSigned result = new research.bwsharingapp.proto.kb.RouterIOUSigned(this);
      if (routerIouBuilder_ == null) {
        result.routerIou_ = routerIou_;
      } else {
        result.routerIou_ = routerIouBuilder_.build();
      }
      result.sign_ = sign_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof research.bwsharingapp.proto.kb.RouterIOUSigned) {
        return mergeFrom((research.bwsharingapp.proto.kb.RouterIOUSigned)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(research.bwsharingapp.proto.kb.RouterIOUSigned other) {
      if (other == research.bwsharingapp.proto.kb.RouterIOUSigned.getDefaultInstance()) return this;
      if (other.hasRouterIou()) {
        mergeRouterIou(other.getRouterIou());
      }
      if (other.getSign() != com.google.protobuf.ByteString.EMPTY) {
        setSign(other.getSign());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      research.bwsharingapp.proto.kb.RouterIOUSigned parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (research.bwsharingapp.proto.kb.RouterIOUSigned) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private research.bwsharingapp.proto.kb.RouterIOU routerIou_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.RouterIOU, research.bwsharingapp.proto.kb.RouterIOU.Builder, research.bwsharingapp.proto.kb.RouterIOUOrBuilder> routerIouBuilder_;
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public boolean hasRouterIou() {
      return routerIouBuilder_ != null || routerIou_ != null;
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public research.bwsharingapp.proto.kb.RouterIOU getRouterIou() {
      if (routerIouBuilder_ == null) {
        return routerIou_ == null ? research.bwsharingapp.proto.kb.RouterIOU.getDefaultInstance() : routerIou_;
      } else {
        return routerIouBuilder_.getMessage();
      }
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public Builder setRouterIou(research.bwsharingapp.proto.kb.RouterIOU value) {
      if (routerIouBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        routerIou_ = value;
        onChanged();
      } else {
        routerIouBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public Builder setRouterIou(
        research.bwsharingapp.proto.kb.RouterIOU.Builder builderForValue) {
      if (routerIouBuilder_ == null) {
        routerIou_ = builderForValue.build();
        onChanged();
      } else {
        routerIouBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public Builder mergeRouterIou(research.bwsharingapp.proto.kb.RouterIOU value) {
      if (routerIouBuilder_ == null) {
        if (routerIou_ != null) {
          routerIou_ =
            research.bwsharingapp.proto.kb.RouterIOU.newBuilder(routerIou_).mergeFrom(value).buildPartial();
        } else {
          routerIou_ = value;
        }
        onChanged();
      } else {
        routerIouBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public Builder clearRouterIou() {
      if (routerIouBuilder_ == null) {
        routerIou_ = null;
        onChanged();
      } else {
        routerIou_ = null;
        routerIouBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public research.bwsharingapp.proto.kb.RouterIOU.Builder getRouterIouBuilder() {
      
      onChanged();
      return getRouterIouFieldBuilder().getBuilder();
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    public research.bwsharingapp.proto.kb.RouterIOUOrBuilder getRouterIouOrBuilder() {
      if (routerIouBuilder_ != null) {
        return routerIouBuilder_.getMessageOrBuilder();
      } else {
        return routerIou_ == null ?
            research.bwsharingapp.proto.kb.RouterIOU.getDefaultInstance() : routerIou_;
      }
    }
    /**
     * <code>.kibbutz.RouterIOU routerIou = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.RouterIOU, research.bwsharingapp.proto.kb.RouterIOU.Builder, research.bwsharingapp.proto.kb.RouterIOUOrBuilder> 
        getRouterIouFieldBuilder() {
      if (routerIouBuilder_ == null) {
        routerIouBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            research.bwsharingapp.proto.kb.RouterIOU, research.bwsharingapp.proto.kb.RouterIOU.Builder, research.bwsharingapp.proto.kb.RouterIOUOrBuilder>(
                getRouterIou(),
                getParentForChildren(),
                isClean());
        routerIou_ = null;
      }
      return routerIouBuilder_;
    }

    private com.google.protobuf.ByteString sign_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes sign = 2;</code>
     */
    public com.google.protobuf.ByteString getSign() {
      return sign_;
    }
    /**
     * <code>bytes sign = 2;</code>
     */
    public Builder setSign(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes sign = 2;</code>
     */
    public Builder clearSign() {
      
      sign_ = getDefaultInstance().getSign();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kibbutz.RouterIOUSigned)
  }

  // @@protoc_insertion_point(class_scope:kibbutz.RouterIOUSigned)
  private static final research.bwsharingapp.proto.kb.RouterIOUSigned DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new research.bwsharingapp.proto.kb.RouterIOUSigned();
  }

  public static research.bwsharingapp.proto.kb.RouterIOUSigned getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouterIOUSigned>
      PARSER = new com.google.protobuf.AbstractParser<RouterIOUSigned>() {
    public RouterIOUSigned parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouterIOUSigned(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouterIOUSigned> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouterIOUSigned> getParserForType() {
    return PARSER;
  }

  public research.bwsharingapp.proto.kb.RouterIOUSigned getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

