// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface RouterIOUReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.RouterIOUReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isValid = 1;</code>
   */
  boolean getIsValid();

  /**
   * <code>int32 statusCode = 2;</code>
   */
  int getStatusCode();
}
