// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface RouterIOUOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.RouterIOU)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  boolean hasIn();
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfo getIn();
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getInOrBuilder();

  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  boolean hasOut();
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfo getOut();
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getOutOrBuilder();

  /**
   * <code>string sign = 3;</code>
   */
  java.lang.String getSign();
  /**
   * <code>string sign = 3;</code>
   */
  com.google.protobuf.ByteString
      getSignBytes();

  /**
   * <code>.kibbutz.ClientIOU clientIou = 4;</code>
   */
  boolean hasClientIou();
  /**
   * <code>.kibbutz.ClientIOU clientIou = 4;</code>
   */
  research.bwsharingapp.proto.kb.ClientIOU getClientIou();
  /**
   * <code>.kibbutz.ClientIOU clientIou = 4;</code>
   */
  research.bwsharingapp.proto.kb.ClientIOUOrBuilder getClientIouOrBuilder();
}
