// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

/**
 * Protobuf type {@code kibbutz.RouterIOU}
 */
public  final class RouterIOU extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kibbutz.RouterIOU)
    RouterIOUOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouterIOU.newBuilder() to construct.
  private RouterIOU(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouterIOU() {
    nonce_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouterIOU(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            research.bwsharingapp.proto.kb.TrafficInfo.Builder subBuilder = null;
            if (in_ != null) {
              subBuilder = in_.toBuilder();
            }
            in_ = input.readMessage(research.bwsharingapp.proto.kb.TrafficInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(in_);
              in_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            research.bwsharingapp.proto.kb.TrafficInfo.Builder subBuilder = null;
            if (out_ != null) {
              subBuilder = out_.toBuilder();
            }
            out_ = input.readMessage(research.bwsharingapp.proto.kb.TrafficInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(out_);
              out_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            research.bwsharingapp.proto.kb.ClientIOUSigned.Builder subBuilder = null;
            if (clientIouSigned_ != null) {
              subBuilder = clientIouSigned_.toBuilder();
            }
            clientIouSigned_ = input.readMessage(research.bwsharingapp.proto.kb.ClientIOUSigned.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clientIouSigned_);
              clientIouSigned_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {

            nonce_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOU_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOU_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            research.bwsharingapp.proto.kb.RouterIOU.class, research.bwsharingapp.proto.kb.RouterIOU.Builder.class);
  }

  public static final int IN_FIELD_NUMBER = 1;
  private research.bwsharingapp.proto.kb.TrafficInfo in_;
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  public boolean hasIn() {
    return in_ != null;
  }
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfo getIn() {
    return in_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : in_;
  }
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getInOrBuilder() {
    return getIn();
  }

  public static final int OUT_FIELD_NUMBER = 2;
  private research.bwsharingapp.proto.kb.TrafficInfo out_;
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  public boolean hasOut() {
    return out_ != null;
  }
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfo getOut() {
    return out_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : out_;
  }
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getOutOrBuilder() {
    return getOut();
  }

  public static final int CLIENTIOUSIGNED_FIELD_NUMBER = 3;
  private research.bwsharingapp.proto.kb.ClientIOUSigned clientIouSigned_;
  /**
   * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
   */
  public boolean hasClientIouSigned() {
    return clientIouSigned_ != null;
  }
  /**
   * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
   */
  public research.bwsharingapp.proto.kb.ClientIOUSigned getClientIouSigned() {
    return clientIouSigned_ == null ? research.bwsharingapp.proto.kb.ClientIOUSigned.getDefaultInstance() : clientIouSigned_;
  }
  /**
   * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
   */
  public research.bwsharingapp.proto.kb.ClientIOUSignedOrBuilder getClientIouSignedOrBuilder() {
    return getClientIouSigned();
  }

  public static final int NONCE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString nonce_;
  /**
   * <code>bytes nonce = 4;</code>
   */
  public com.google.protobuf.ByteString getNonce() {
    return nonce_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (in_ != null) {
      output.writeMessage(1, getIn());
    }
    if (out_ != null) {
      output.writeMessage(2, getOut());
    }
    if (clientIouSigned_ != null) {
      output.writeMessage(3, getClientIouSigned());
    }
    if (!nonce_.isEmpty()) {
      output.writeBytes(4, nonce_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (in_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIn());
    }
    if (out_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOut());
    }
    if (clientIouSigned_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getClientIouSigned());
    }
    if (!nonce_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, nonce_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof research.bwsharingapp.proto.kb.RouterIOU)) {
      return super.equals(obj);
    }
    research.bwsharingapp.proto.kb.RouterIOU other = (research.bwsharingapp.proto.kb.RouterIOU) obj;

    boolean result = true;
    result = result && (hasIn() == other.hasIn());
    if (hasIn()) {
      result = result && getIn()
          .equals(other.getIn());
    }
    result = result && (hasOut() == other.hasOut());
    if (hasOut()) {
      result = result && getOut()
          .equals(other.getOut());
    }
    result = result && (hasClientIouSigned() == other.hasClientIouSigned());
    if (hasClientIouSigned()) {
      result = result && getClientIouSigned()
          .equals(other.getClientIouSigned());
    }
    result = result && getNonce()
        .equals(other.getNonce());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIn()) {
      hash = (37 * hash) + IN_FIELD_NUMBER;
      hash = (53 * hash) + getIn().hashCode();
    }
    if (hasOut()) {
      hash = (37 * hash) + OUT_FIELD_NUMBER;
      hash = (53 * hash) + getOut().hashCode();
    }
    if (hasClientIouSigned()) {
      hash = (37 * hash) + CLIENTIOUSIGNED_FIELD_NUMBER;
      hash = (53 * hash) + getClientIouSigned().hashCode();
    }
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getNonce().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static research.bwsharingapp.proto.kb.RouterIOU parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(research.bwsharingapp.proto.kb.RouterIOU prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kibbutz.RouterIOU}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kibbutz.RouterIOU)
      research.bwsharingapp.proto.kb.RouterIOUOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOU_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              research.bwsharingapp.proto.kb.RouterIOU.class, research.bwsharingapp.proto.kb.RouterIOU.Builder.class);
    }

    // Construct using research.bwsharingapp.proto.kb.RouterIOU.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (inBuilder_ == null) {
        in_ = null;
      } else {
        in_ = null;
        inBuilder_ = null;
      }
      if (outBuilder_ == null) {
        out_ = null;
      } else {
        out_ = null;
        outBuilder_ = null;
      }
      if (clientIouSignedBuilder_ == null) {
        clientIouSigned_ = null;
      } else {
        clientIouSigned_ = null;
        clientIouSignedBuilder_ = null;
      }
      nonce_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return research.bwsharingapp.proto.kb.KibbutzProto.internal_static_kibbutz_RouterIOU_descriptor;
    }

    public research.bwsharingapp.proto.kb.RouterIOU getDefaultInstanceForType() {
      return research.bwsharingapp.proto.kb.RouterIOU.getDefaultInstance();
    }

    public research.bwsharingapp.proto.kb.RouterIOU build() {
      research.bwsharingapp.proto.kb.RouterIOU result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public research.bwsharingapp.proto.kb.RouterIOU buildPartial() {
      research.bwsharingapp.proto.kb.RouterIOU result = new research.bwsharingapp.proto.kb.RouterIOU(this);
      if (inBuilder_ == null) {
        result.in_ = in_;
      } else {
        result.in_ = inBuilder_.build();
      }
      if (outBuilder_ == null) {
        result.out_ = out_;
      } else {
        result.out_ = outBuilder_.build();
      }
      if (clientIouSignedBuilder_ == null) {
        result.clientIouSigned_ = clientIouSigned_;
      } else {
        result.clientIouSigned_ = clientIouSignedBuilder_.build();
      }
      result.nonce_ = nonce_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof research.bwsharingapp.proto.kb.RouterIOU) {
        return mergeFrom((research.bwsharingapp.proto.kb.RouterIOU)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(research.bwsharingapp.proto.kb.RouterIOU other) {
      if (other == research.bwsharingapp.proto.kb.RouterIOU.getDefaultInstance()) return this;
      if (other.hasIn()) {
        mergeIn(other.getIn());
      }
      if (other.hasOut()) {
        mergeOut(other.getOut());
      }
      if (other.hasClientIouSigned()) {
        mergeClientIouSigned(other.getClientIouSigned());
      }
      if (other.getNonce() != com.google.protobuf.ByteString.EMPTY) {
        setNonce(other.getNonce());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      research.bwsharingapp.proto.kb.RouterIOU parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (research.bwsharingapp.proto.kb.RouterIOU) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private research.bwsharingapp.proto.kb.TrafficInfo in_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> inBuilder_;
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public boolean hasIn() {
      return inBuilder_ != null || in_ != null;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo getIn() {
      if (inBuilder_ == null) {
        return in_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : in_;
      } else {
        return inBuilder_.getMessage();
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder setIn(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (inBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        in_ = value;
        onChanged();
      } else {
        inBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder setIn(
        research.bwsharingapp.proto.kb.TrafficInfo.Builder builderForValue) {
      if (inBuilder_ == null) {
        in_ = builderForValue.build();
        onChanged();
      } else {
        inBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder mergeIn(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (inBuilder_ == null) {
        if (in_ != null) {
          in_ =
            research.bwsharingapp.proto.kb.TrafficInfo.newBuilder(in_).mergeFrom(value).buildPartial();
        } else {
          in_ = value;
        }
        onChanged();
      } else {
        inBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public Builder clearIn() {
      if (inBuilder_ == null) {
        in_ = null;
        onChanged();
      } else {
        in_ = null;
        inBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo.Builder getInBuilder() {
      
      onChanged();
      return getInFieldBuilder().getBuilder();
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getInOrBuilder() {
      if (inBuilder_ != null) {
        return inBuilder_.getMessageOrBuilder();
      } else {
        return in_ == null ?
            research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : in_;
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo in = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> 
        getInFieldBuilder() {
      if (inBuilder_ == null) {
        inBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder>(
                getIn(),
                getParentForChildren(),
                isClean());
        in_ = null;
      }
      return inBuilder_;
    }

    private research.bwsharingapp.proto.kb.TrafficInfo out_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> outBuilder_;
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public boolean hasOut() {
      return outBuilder_ != null || out_ != null;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo getOut() {
      if (outBuilder_ == null) {
        return out_ == null ? research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : out_;
      } else {
        return outBuilder_.getMessage();
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder setOut(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (outBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        out_ = value;
        onChanged();
      } else {
        outBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder setOut(
        research.bwsharingapp.proto.kb.TrafficInfo.Builder builderForValue) {
      if (outBuilder_ == null) {
        out_ = builderForValue.build();
        onChanged();
      } else {
        outBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder mergeOut(research.bwsharingapp.proto.kb.TrafficInfo value) {
      if (outBuilder_ == null) {
        if (out_ != null) {
          out_ =
            research.bwsharingapp.proto.kb.TrafficInfo.newBuilder(out_).mergeFrom(value).buildPartial();
        } else {
          out_ = value;
        }
        onChanged();
      } else {
        outBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public Builder clearOut() {
      if (outBuilder_ == null) {
        out_ = null;
        onChanged();
      } else {
        out_ = null;
        outBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfo.Builder getOutBuilder() {
      
      onChanged();
      return getOutFieldBuilder().getBuilder();
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    public research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getOutOrBuilder() {
      if (outBuilder_ != null) {
        return outBuilder_.getMessageOrBuilder();
      } else {
        return out_ == null ?
            research.bwsharingapp.proto.kb.TrafficInfo.getDefaultInstance() : out_;
      }
    }
    /**
     * <code>.kibbutz.TrafficInfo out = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder> 
        getOutFieldBuilder() {
      if (outBuilder_ == null) {
        outBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            research.bwsharingapp.proto.kb.TrafficInfo, research.bwsharingapp.proto.kb.TrafficInfo.Builder, research.bwsharingapp.proto.kb.TrafficInfoOrBuilder>(
                getOut(),
                getParentForChildren(),
                isClean());
        out_ = null;
      }
      return outBuilder_;
    }

    private research.bwsharingapp.proto.kb.ClientIOUSigned clientIouSigned_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.ClientIOUSigned, research.bwsharingapp.proto.kb.ClientIOUSigned.Builder, research.bwsharingapp.proto.kb.ClientIOUSignedOrBuilder> clientIouSignedBuilder_;
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public boolean hasClientIouSigned() {
      return clientIouSignedBuilder_ != null || clientIouSigned_ != null;
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public research.bwsharingapp.proto.kb.ClientIOUSigned getClientIouSigned() {
      if (clientIouSignedBuilder_ == null) {
        return clientIouSigned_ == null ? research.bwsharingapp.proto.kb.ClientIOUSigned.getDefaultInstance() : clientIouSigned_;
      } else {
        return clientIouSignedBuilder_.getMessage();
      }
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public Builder setClientIouSigned(research.bwsharingapp.proto.kb.ClientIOUSigned value) {
      if (clientIouSignedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientIouSigned_ = value;
        onChanged();
      } else {
        clientIouSignedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public Builder setClientIouSigned(
        research.bwsharingapp.proto.kb.ClientIOUSigned.Builder builderForValue) {
      if (clientIouSignedBuilder_ == null) {
        clientIouSigned_ = builderForValue.build();
        onChanged();
      } else {
        clientIouSignedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public Builder mergeClientIouSigned(research.bwsharingapp.proto.kb.ClientIOUSigned value) {
      if (clientIouSignedBuilder_ == null) {
        if (clientIouSigned_ != null) {
          clientIouSigned_ =
            research.bwsharingapp.proto.kb.ClientIOUSigned.newBuilder(clientIouSigned_).mergeFrom(value).buildPartial();
        } else {
          clientIouSigned_ = value;
        }
        onChanged();
      } else {
        clientIouSignedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public Builder clearClientIouSigned() {
      if (clientIouSignedBuilder_ == null) {
        clientIouSigned_ = null;
        onChanged();
      } else {
        clientIouSigned_ = null;
        clientIouSignedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public research.bwsharingapp.proto.kb.ClientIOUSigned.Builder getClientIouSignedBuilder() {
      
      onChanged();
      return getClientIouSignedFieldBuilder().getBuilder();
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    public research.bwsharingapp.proto.kb.ClientIOUSignedOrBuilder getClientIouSignedOrBuilder() {
      if (clientIouSignedBuilder_ != null) {
        return clientIouSignedBuilder_.getMessageOrBuilder();
      } else {
        return clientIouSigned_ == null ?
            research.bwsharingapp.proto.kb.ClientIOUSigned.getDefaultInstance() : clientIouSigned_;
      }
    }
    /**
     * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        research.bwsharingapp.proto.kb.ClientIOUSigned, research.bwsharingapp.proto.kb.ClientIOUSigned.Builder, research.bwsharingapp.proto.kb.ClientIOUSignedOrBuilder> 
        getClientIouSignedFieldBuilder() {
      if (clientIouSignedBuilder_ == null) {
        clientIouSignedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            research.bwsharingapp.proto.kb.ClientIOUSigned, research.bwsharingapp.proto.kb.ClientIOUSigned.Builder, research.bwsharingapp.proto.kb.ClientIOUSignedOrBuilder>(
                getClientIouSigned(),
                getParentForChildren(),
                isClean());
        clientIouSigned_ = null;
      }
      return clientIouSignedBuilder_;
    }

    private com.google.protobuf.ByteString nonce_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes nonce = 4;</code>
     */
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }
    /**
     * <code>bytes nonce = 4;</code>
     */
    public Builder setNonce(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes nonce = 4;</code>
     */
    public Builder clearNonce() {
      
      nonce_ = getDefaultInstance().getNonce();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:kibbutz.RouterIOU)
  }

  // @@protoc_insertion_point(class_scope:kibbutz.RouterIOU)
  private static final research.bwsharingapp.proto.kb.RouterIOU DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new research.bwsharingapp.proto.kb.RouterIOU();
  }

  public static research.bwsharingapp.proto.kb.RouterIOU getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouterIOU>
      PARSER = new com.google.protobuf.AbstractParser<RouterIOU>() {
    public RouterIOU parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouterIOU(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouterIOU> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RouterIOU> getParserForType() {
    return PARSER;
  }

  public research.bwsharingapp.proto.kb.RouterIOU getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

