// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface RouterIOUOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.RouterIOU)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  boolean hasIn();
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfo getIn();
  /**
   * <code>.kibbutz.TrafficInfo in = 1;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getInOrBuilder();

  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  boolean hasOut();
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfo getOut();
  /**
   * <code>.kibbutz.TrafficInfo out = 2;</code>
   */
  research.bwsharingapp.proto.kb.TrafficInfoOrBuilder getOutOrBuilder();

  /**
   * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
   */
  boolean hasClientIouSigned();
  /**
   * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
   */
  research.bwsharingapp.proto.kb.ClientIOUSigned getClientIouSigned();
  /**
   * <code>.kibbutz.ClientIOUSigned clientIouSigned = 3;</code>
   */
  research.bwsharingapp.proto.kb.ClientIOUSignedOrBuilder getClientIouSignedOrBuilder();

  /**
   * <code>bytes nonce = 4;</code>
   */
  com.google.protobuf.ByteString getNonce();
}
