// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface RouterIOUSignedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.RouterIOUSigned)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kibbutz.RouterIOU routerIou = 1;</code>
   */
  boolean hasRouterIou();
  /**
   * <code>.kibbutz.RouterIOU routerIou = 1;</code>
   */
  research.bwsharingapp.proto.kb.RouterIOU getRouterIou();
  /**
   * <code>.kibbutz.RouterIOU routerIou = 1;</code>
   */
  research.bwsharingapp.proto.kb.RouterIOUOrBuilder getRouterIouOrBuilder();

  /**
   * <code>bytes sign = 2;</code>
   */
  com.google.protobuf.ByteString getSign();
}
