// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface TrafficInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.TrafficInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 pkts = 1;</code>
   */
  long getPkts();

  /**
   * <code>int64 bytes = 2;</code>
   */
  long getBytes();

  /**
   * <code>string src = 3;</code>
   */
  java.lang.String getSrc();
  /**
   * <code>string src = 3;</code>
   */
  com.google.protobuf.ByteString
      getSrcBytes();

  /**
   * <code>string dst = 4;</code>
   */
  java.lang.String getDst();
  /**
   * <code>string dst = 4;</code>
   */
  com.google.protobuf.ByteString
      getDstBytes();
}
