// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kibbutz.proto

package research.bwsharingapp.proto.kb;

public interface UserDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kibbutz.UserData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string deviceId = 2;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>string deviceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>bytes pubKey = 3;</code>
   */
  com.google.protobuf.ByteString getPubKey();
}
